name: run-tests
on:
  push:
    branches:
    - QA
jobs:
  hold:
    environment:
      name: approval
    runs-on: ubuntu-latest
    steps:
    - run: echo 'approved'
  test:
    defaults:
      run:
        working-directory: "/__w/diffusion-marketplace/diffusion-marketplace/~/repo"
    runs-on: ubuntu-latest
    container:
      image: circleci/ruby:2.7.5-node-browsers
      env:
        RAILS_ENV: test
        MAX_THREADS: 2
        WEB_CONCURRENCY: 1
        POSTGRES_PASSWORD: mysecretlocalpassword
        POSTGRES_USER: postgres
        POSTGRES_DB: web_app
        POSTGRES_HOST: 127.0.0.1
        POSTGRES_PORT: 5432
        REDIS_HOST: redis_test
        REDIS_PORT: 6379
        REDIS_DB_ID: 0
        BUNDLE_JOBS: 3
        BUNDLE_RETRY: 3
        BUNDLE_PATH: vendor/bundle
    services:
      postgres:
        image: cimg/postgres:12.10
        env:
          POSTGRES_PASSWORD: mysecretlocalpassword
          POSTGRES_USER: postgres
          POSTGRES_DB: web_app
      redis:
        image: redis
    needs:
    - hold
    steps:
    # This Docker file changes sets USER to circleci instead of using the default user, so we need to update file permissions for this image to work on GH Actions.
    # See https://docs.github.com/actions/using-github-hosted-runners/about-github-hosted-runners#docker-container-filesystem
    - name: Create working directory
      run: mkdir -p /__w/diffusion-marketplace/diffusion-marketplace/~/repo
    - name: Setup file system permissions
      run: sudo chmod -R 777 $GITHUB_WORKSPACE /github /__w/_temp
    - uses: actions/checkout@v3.3.0
    - name: restore_cache
      uses: actions/cache@v3.3.1
      with:
        key: v1-dependencies-{{ checksum "Gemfile.lock" }}
        restore-keys: |-
          v1-dependencies-{{ checksum "Gemfile.lock" }}
          v1-dependencies-
        path: "./vendor/bundle"
    - name: install dependencies
      run: |-
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo apt-get update --allow-releaseinfo-change
        sudo apt-get install libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x
        gem install bundler
